spring.application.name=admin

# === Server ===
server.port=8081

# === Database ===
spring.datasource.url=jdbc:postgresql://192.168.2.200:5432/wpoms-dev
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Enable auto DDL update
spring.jpa.hibernate.ddl-auto=update

# Show SQL queries in console (to see what Hibernate is doing)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true